### ISSUE TITLE
Predicted results on the test set

### ISSUE THREAD

**Issue by kosuke1701** [loriqing/Label-Reasoning-Network#1]
Thanks for sharing your codes and model!

I want to compute different metric, e.g. MRR, of the results reported in Table 1 of the paper. Would it be possible to share us predicted labels and scores of your model on the test set of ultra-fine entity typing dataset?

Best regards.

**Comment by loriqing** [comment]
> 

Hi, we have uploaded predictions of _LRN_  to the directory ./output/, including both test set and development set of ufet.
You can use any metric to evaluate it.

**Comment by kosuke1701** [comment]
Thanks a lot!
Just to confirm, did you use the model metioned in project README (https://drive.google.com/drive/folders/1in0OANpIBq6BJC-HNNRVSDlcN1J1oTuq?usp=sharing) to generate these outputs?

**Comment by loriqing** [comment]
> Thanks a lot! Just to confirm, did you use the model metioned in project README (https://drive.google.com/drive/folders/1in0OANpIBq6BJC-HNNRVSDlcN1J1oTuq?usp=sharing) to generate these outputs?
Yes

**Comment by loriqing** [comment]
> Thanks a lot! Just to confirm, did you use the model metioned in project README (https://drive.google.com/drive/folders/1in0OANpIBq6BJC-HNNRVSDlcN1J1oTuq?usp=sharing) to generate these outputs?

Yes

**Comment by kosuke1701** [comment]
Thank you for the quick response. It was very helpful.
